config/routes.rb
Rails.application.routes.draw do

  get '/courses/all', to: 'courses#index_all'
  resources :courses

  patch 'courses/:id/enroll', to: 'courses#enroll', as: 'enroll_course'

  get 'categories/:category', to: 'courses#index', as: 'category'

  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/categorize.rb
class Categorize < ActiveRecord::Base
  belongs_to :course
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :categorize
  has_many :courses, through: :categorize

end

app/models/course.rb
class Course < ActiveRecord::Base

  has_many :categorize
  has_many :categories, through: :categorize
  has_and_belongs_to_many :users,  :join_table => :users_courses

  validates_presence_of :name, :code, :start_date, :end_date

  before_save :sanitize_content

  def all_categories=(names)
    self.categories = names.split(",").map do |name|
        Category.where(name: name.downcase.strip.gsub(/\s+/, "-")).first_or_create!
    end
  end

  def all_categories
    self.categories.map(&:name).join(", ")
  end

  def self.categorized(name)
    Category.find_by_name!(name).courses
  end

  def sanitize_content
    self.code = self.code.gsub(/\s+/, "").downcase
  end

  def enrolled?(current_user)
    return false if current_user.nil? || !current_user.student?
    self.users.find_by_id(current_user.id).present?
  end

  def can_enroll?(current_user)
    (current_user.nil? || current_user.student?) ? true : false
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:student, :professor, :admin]
  after_initialize :set_default_role, :if => :new_record?

  has_and_belongs_to_many :courses,  :join_table => :users_courses

  validates_presence_of :email, :role

  def set_default_role
    self.role ||= :student
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,# :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include Pundit

  # Verify that controller actions are authorized. Optional, but good.
  # after_action :verify_authorized,  except: [:index, :show]
  # after_action :verify_policy_scoped, only: :index

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:error] = "You are not authorized to perform this action."
    redirect_to request.headers["Referer"] || root_path
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  respond_to :html, :json
  before_action :set_course, only: [:show, :edit, :update, :destroy, :enroll]

  before_filter :authenticate_user!, except: [:index, :index_all, :show]

  def index
    if params[:category]
      @courses = Course.categorized(params[:category])
    else
      @courses = policy_scope(Course)
    end
    respond_with(@courses)
  end

  def index_all
    @courses = Course.all
    respond_with(@courses, template: 'courses/index')
  end

  def show
    respond_with(@course)
  end

  def new
    @course = Course.new
    authorize @course
    respond_with(@course)
  end

  def edit
    authorize @course
  end

  def create
    @course = Course.new(course_params)
    @course.users << User.find(current_user.id)
    authorize @course
    flash[:notice] = 'Course was successfully created.' if @course.save
    respond_with(@course)
  end

  def update
    authorize @course
    flash[:notice] = 'Course was successfully updated.' if @course.update(course_params)
    respond_with(@course)
  end

  def destroy
    authorize @course
    @course.destroy
    respond_with(@course)
  end

  def enroll
    @course.users << current_user
    @course.save
  end

  private
    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:name, :code, :description, :start_date, :end_date, :duration, :grade_point, :syllabus, :all_categories)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper

  def category_links(categories)
    categories.split(",").map{|category| link_to category.strip, category_path(category.strip) }.join(", ")
  end

end

app/helpers/visitor_helper.rb
module VisitorHelper

  def admin_email()
    User.where("role = ?", User.roles[:admin]).first.email rescue 'No Admin'
  end

end

app/views/courses/_enroll.html.haml
= simple_form_for(@course, url: enroll_course_path, method: :patch, remote: true) do |f|
  = f.submit "Enroll", class: "btn btn-primary"

app/views/courses/_form.html.haml
.row
  .col-md-6
    = simple_form_for @course, html: { class: 'form-horizontal' }, wrapper: :horizontal_form,  |
      wrapper_mappings: {                                   |
        check_boxes: :horizontal_radio_and_checkboxes,      |
        radio_buttons: :horizontal_radio_and_checkboxes,    |
        file: :horizontal_file_input,                       |
        boolean: :horizontal_boolean                        |
      } do |f|                                              |
      = f.error_notification

      .form-inputs
        = f.input :name
        = f.input :code
        = f.input :description
        = f.input :start_date
        = f.input :end_date
        = f.input :duration
        = f.input :grade_point
        = f.input :syllabus
        = f.input :all_categories

      .form-actions
        = f.button :submit, class: 'btn-primary'

app/views/courses/edit.html.haml
%h1 Editing course

= render 'form'

= link_to 'Show', @course
\|
= link_to 'Back', courses_path

app/views/courses/enroll.js.erb
$("#course-enroll").html("Enrolled!")

app/views/courses/index.html.haml
.row
  %h1 Course Listing
  - if user_signed_in?
    - if action_name == 'index_all'
      %p View #{ link_to 'My Courses.', courses_path }
    - else
      %p View #{ link_to 'All Courses.', courses_all_path }


- @courses.each do |course|
  .row.course-list-item
    .col-md-3.course-list-item-meta
      %h5
        Start Date:
        = course.start_date
      %h5
        End Date:
        = course.start_date
    .col-md-9
      %h6= course.code
      %h2= link_to course.name, course
      %div= course.description

%br

- if policy(:course).create?
  = link_to 'New Course', new_course_path

app/views/courses/new.html.haml
%h1 New course

= render 'form'

= link_to 'Back', courses_path

app/views/courses/show.html.haml
%p#notice= notice

%h4= @course.code
.row.course-title
  %h1= @course.name
  - if policy(@course).enrolled?
    #course-enroll
      Enrolled!
  -elsif policy(:course).enroll?
    #course-enroll
      = render 'enroll'
%p
  %b Categories:
  = raw category_links(@course.all_categories)
%p
  %b Start date:
  = @course.start_date
  %br
  %b End date:
  = @course.end_date
  %br
  %b Duration:
  = @course.duration
%h3 Description:
= @course.description

%br
%br
%p
  %b Grade point:
  = @course.grade_point
%p
  %b Syllabus:
  = @course.syllabus


- if policy(:course).update?
  = link_to 'Edit', edit_course_path(@course)
  \|
- if policy(:course).enroll?
  - unless @course.enrolled?(current_user)
    = link_to 'Enroll', enroll_course_path(@course)
  - else
    = 'Enrolled'

  \|
= link_to 'Back', courses_path

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Course', courses_path %></li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
<!--     <li><%= link_to 'Admin', '/admin' %></li> -->
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Online University'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Online University'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      .container
        .row
          .col-md-12
            = render 'layouts/messages'
            = yield

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.haml
%h3 Welcome to Online University
.jumbotron
  - if user_signed_in?
    - if current_user.professor?
      %p Let's start by creating a new course.
      %p= link_to 'Create Course.', new_course_path
    - elsif current_user.student?
      %p
        Let's start by browsing the #{link_to 'Courses', courses_all_path}.
      %p
        You are currently registered as a Student.
        %br
        Please contact admin
        %b= admin_email
        in case you want to change your role to Professor.
    - elsif current_user.admin?
      %p
        = link_to 'Courses:', courses_path
        = Course.count
        registered
  - else
    %p
      = link_to 'Courses:', courses_path
      = Course.count
      registered